### ConfigMap
apiVersion: v1
kind: ConfigMap
metadata: 
  name: payment
  namespace: roboshop
  labels:
    component: payment
    project: roboshop
    tier: app
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
